// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTF-rgBXs6NJlTmgvS9bh003USL1qJofg',
    appId: '1:1013133387129:web:cd519a7b237e51e45ebba8',
    messagingSenderId: '1013133387129',
    projectId: 'eleven-project-ea1d5',
    authDomain: 'eleven-project-ea1d5.firebaseapp.com',
    storageBucket: 'eleven-project-ea1d5.appspot.com',
    measurementId: 'G-4P51P7NY71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC5c3O0_7xjzECL_0m-T_GszR03GqkKPM',
    appId: '1:1013133387129:android:b94917ebf93795e55ebba8',
    messagingSenderId: '1013133387129',
    projectId: 'eleven-project-ea1d5',
    storageBucket: 'eleven-project-ea1d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD41_1TBOlbenIFyjZIVLgmQL_6msWyzKM',
    appId: '1:1013133387129:ios:a2acf9db390037e85ebba8',
    messagingSenderId: '1013133387129',
    projectId: 'eleven-project-ea1d5',
    storageBucket: 'eleven-project-ea1d5.appspot.com',
    iosBundleId: 'com.example.elevenProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD41_1TBOlbenIFyjZIVLgmQL_6msWyzKM',
    appId: '1:1013133387129:ios:a2acf9db390037e85ebba8',
    messagingSenderId: '1013133387129',
    projectId: 'eleven-project-ea1d5',
    storageBucket: 'eleven-project-ea1d5.appspot.com',
    iosBundleId: 'com.example.elevenProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTF-rgBXs6NJlTmgvS9bh003USL1qJofg',
    appId: '1:1013133387129:web:479dd136667799d25ebba8',
    messagingSenderId: '1013133387129',
    projectId: 'eleven-project-ea1d5',
    authDomain: 'eleven-project-ea1d5.firebaseapp.com',
    storageBucket: 'eleven-project-ea1d5.appspot.com',
    measurementId: 'G-TZ6M3ZW8YW',
  );
}
